### ISSUE TITLE
Turn debug mode off by default

### ISSUE THREAD

**Issue by JulienBacquart** [Inserm-IST/MTW-MeSH-Docker#2]

**Comment by filak** [comment]
The debug mode is always OFF when using the mtw_server.py and mtw_worker.py

**Comment by JulienBacquart** [comment]
Hi @filak ,

If you look into the Compose file, you can see that I launch MTW with the following command:

```bash
python mtw-server.py --host 0.0.0.0 $${DEBUG} & python mtw-worker.py $${DEBUG}
```

These issues are more for me to remember to clean up the stuff I left during the development phase, and making it production ready.

In this case I needed to test what is the default value of an env variable if it's not set (because it's commented):
```dockerfile
    environment:
      # - DEBUG=--debug
```
Turns out it's a blank string, so it works.
